name: Deploy on Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Cache
        id: cache-primes
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache
            ~/.npm
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Run lint
        run: npm run lint

      - name: Setup Firebase Hosting
        uses: firebaseextended/action-hosting-deploy@v0
        with:
          channelID: live
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.GOOGLE_CREDENTIALS }}
          projectId: ${{ secrets.GCP_PROJECT_ID }}
          expires: 30d
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks
