name: Deploy on Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Firebase Hosting
        uses: firebaseextended/action-hosting-deploy@v0
        with:
          channelID: live
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.GOOGLE_CREDENTIALS }}
          projectId: ${{ secrets.GCP_PROJECT_ID }}
          expires: 30d
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks
